drop table if exists brand CASCADE;
drop table if exists category CASCADE;
drop table if exists product CASCADE;
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start with 1 increment by 1;
create table brand (id bigint generated by default as identity, name varchar(255), primary key (id));
create table category (id bigint generated by default as identity, name varchar(255), primary key (id));
create table product (id bigint generated by default as identity, name varchar(255), price numeric(19,2), brand_id bigint, category_id bigint, primary key (id));
alter table product add constraint FK_PRODUCT_BRAND foreign key (brand_id) references brand;
alter table product add constraint FK_PRODUCT_CATEGORY foreign key (category_id) references category;

-- 브랜드
INSERT INTO brand (name) VALUES ('A');
INSERT INTO brand (name) VALUES ('B');
INSERT INTO brand (name) VALUES ('C');


-- 카테고리
INSERT INTO category (name) VALUES ('상의');
INSERT INTO category (name) VALUES ('아우터');
INSERT INTO category (name) VALUES ('바지');


-- 제품

-- A 브랜드 제품
INSERT INTO product (name, price, brand_id, category_id) VALUES ('a_상의', 11200, 1, 1);
INSERT INTO product (name, price, brand_id, category_id) VALUES ('a_아우터', 5500, 1, 2);
INSERT INTO product (name, price, brand_id, category_id) VALUES ('a_바지', 4200, 1, 3);

-- B 브랜드 제품
INSERT INTO product (name, price, brand_id, category_id) VALUES ('b_상의', 10500, 2, 1);
INSERT INTO product (name, price, brand_id, category_id) VALUES ('b_아우터', 5900, 2, 2);
INSERT INTO product (name, price, brand_id, category_id) VALUES ('b_바지', 3800, 2, 3);

-- C 브랜드 제품
INSERT INTO product (name, price, brand_id, category_id) VALUES ('c_상의', 10000, 3, 1);
INSERT INTO product (name, price, brand_id, category_id) VALUES ('c_아우터', 6200, 3, 2);
INSERT INTO product (name, price, brand_id, category_id) VALUES ('c_바지', 3300, 3, 3);
INSERT INTO product (name, price, brand_id, category_id) VALUES ('c_바지2', 1300, 3, 3);

